---
title: "HW2_maps"
author: "yhui"
date: "10/3/2019"
output: html_document
---

```{r setup, include=FALSE}
require(rgdal)
require(leaflet)
require(leaflet.extras)

require(dplyr)
require(readxl)
require(stringr)
```

# Getting Spatial Data to draw polygons on world map

```{r, loading}
cds.load <- readOGR("./cb_2015_us_cd114_500k/cb_2015_us_cd114_500k.shp", layer = "cb_2015_us_cd114_500k", GDAL1_integer64_policy = TRUE)
plot(cds.load)

```

# Merging Table Data to my shapefile

```{r, merging}
op_data<- read_excel("Geographies_of_Opportunity_Ranking_Well_Being_by_Congressional_District_(114th_Congress).xlsx") %>%
  mutate(Number = str_pad(Number, 4, pad = "0"))
op_white<-op_data[op_data$`White (%)`>50,]
op_nonwhite<-op_data[op_data$`White (%)`<=50,]
# Create 2 data tables with different portions of White #Population
cds1 <- cds.load[cds.load$GEOID  %in% op_white$Number,]
cds2 <- cds.load[cds.load$GEOID  %in% op_nonwhite$Number,]
cds1@data <- merge(cds1@data, op_white, sort = FALSE, by.x = "GEOID", by.y = "Number")
cds2@data <- merge(cds2@data, op_nonwhite, sort = FALSE, by.x = "GEOID", by.y = "Number")
```

# Blank map with basemap,overlay groups, and layer control

```{r, controls}
leaflet() %>%
  # Use world map as my basemap
  addProviderTiles("Esri.WorldImagery",group = "World Imagery") %>%
  addProviderTiles("Stamen.TonerLite", group = "Toner Lite") %>%
  #Design overlay groups: 2 different polygons representing 2 #populations with different White portion
  addPolygons(data=cds1,weight=0.5,color="#ff00f8",fillColor="#6474e5",fillOpacity=0.8,group = "white over 50%")%>%
  addPolygons(data=cds2,weight=0.5,color="#2ffb01",fillColor="#6474e7",fillOpacity=0.8,group = "white below 50%")%>%
  # Layers control
  addLayersControl(
    baseGroups = c("World Imagery",  "Toner Lite"),
    overlayGroups = c("white over 50%","white below 50%"),
    options = layersControlOptions(collapsed = FALSE)
  )

```

#Map with lines: Lines with different widths indicating different scalerank of the rivers on world map

```{r, lines}
#import data recording river information
rivers <- readOGR("./ne_10m_rivers_lake_centerlines")
# define a set of widths to be used later in addPolylines ()
width<-c(1,2,3,4,5,6,7,8,9,10)/5
leaflet(data = rivers) %>%
  addProviderTiles("Esri.WorldImagery", options = providerTileOptions(noWrap = TRUE)) %>%
  #river with higher scalerank is drawn in wider line
  addPolylines(color = "#d80505",weight=width[rivers@data$scalerank],opacity=0.7,popup = ~name)
```


